Fix profile.d environment loading to check files exist, etc.

diff --git a/dotfiles/profile.d/environment b/dotfiles/profile.d/environment
--- a/dotfiles/profile.d/environment
+++ b/dotfiles/profile.d/environment
@@ -1,44 +1,69 @@
-source ${HOME}/.profile.d/global.functions
-source ${HOME}/.profile.d/global.env
-source ${HOME}/.profile.d/global.aliases
+function sourceProfileInit() {
+  if [ "$#" -ne 1 ]; then
+    >&2 echo "Error: Expected one argument, received $# for ${FUNCNAME}"
+    >&2 echo "Usage: ${FUNCNAME} FILE_INSIDE_PROFILE_DIR"
+    return 1
+  fi
 
-source ${HOME}/.profile.d/work.functions
+  local -r path="${HOME}/.profile.d/${1}"
 
-source ${HOME}/.profile.d/all.aliases
-source ${HOME}/.profile.d/personal.aliases
-source ${HOME}/.profile.d/oss.aliases
-source ${HOME}/.profile.d/gerrit.aliases
-source ${HOME}/.profile.d/haskell.aliases
-source ${HOME}/.profile.d/ruby.aliases
-source ${HOME}/.profile.d/scala.aliases
-source ${HOME}/.profile.d/work.aliases
+  if [ -f "${path}" ]; then
+    source "${path}"
+  fi
+}
 
-source ${HOME}/.profile.d/nix.env
-source ${HOME}/.profile.d/clojure.env
-source ${HOME}/.profile.d/ec2.env
-source ${HOME}/.profile.d/erlang.env
-source ${HOME}/.profile.d/haskell.env
-source ${HOME}/.profile.d/github.env
-source ${HOME}/.profile.d/java.env
-source ${HOME}/.profile.d/javascript.env
-source ${HOME}/.profile.d/jruby.env
-source ${HOME}/.profile.d/node.env
-source ${HOME}/.profile.d/opa.env
-source ${HOME}/.profile.d/python.env
-source ${HOME}/.profile.d/ruby.env
-source ${HOME}/.profile.d/scala.env
-source ${HOME}/.profile.d/ssh.env
-source ${HOME}/.profile.d/personal.env
-source ${HOME}/.profile.d/work.env
-source ${HOME}/.profile.d/adium.env
+sourceProfileInit "global.functions"
+sourceProfileInit "global.env"
+sourceProfileInit "global.aliases"
 
-if [ "${PLATFORM}" == "Darwin" ]; then
-  source ${HOME}/.profile.d/osx.env
-  source ${HOME}/.profile.d/osx.functions
-  source ${HOME}/.profile.d/osx.aliases
+sourceProfileInit "work.functions"
+sourceProfileInit "personal.functions"
+sourceProfileInit "oss.functions"
+sourceProfileInit "haskell.functions"
+sourceProfileInit "nix.functions"
+sourceProfileInit "erlang.functions"
+sourceProfileInit "scala.functions"
+sourceProfileInit "ruby.functions"
+sourceProfileInit "python.functions"
+sourceProfileInit "github.functions"
+sourceProfileInit "ssh.functions"
+
+sourceProfileInit "nix.env"
+sourceProfileInit "clojure.env"
+sourceProfileInit "ec2.env"
+sourceProfileInit "erlang.env"
+sourceProfileInit "haskell.env"
+sourceProfileInit "github.env"
+sourceProfileInit "java.env"
+sourceProfileInit "javascript.env"
+sourceProfileInit "jruby.env"
+sourceProfileInit "node.env"
+sourceProfileInit "opa.env"
+sourceProfileInit "python.env"
+sourceProfileInit "ruby.env"
+sourceProfileInit "scala.env"
+sourceProfileInit "ssh.env"
+sourceProfileInit "personal.env"
+sourceProfileInit "work.env"
+sourceProfileInit "adium.env"
+
+sourceProfileInit "all.aliases"
+sourceProfileInit "personal.aliases"
+sourceProfileInit "oss.aliases"
+sourceProfileInit "haskell.aliases"
+sourceProfileInit "ruby.aliases"
+sourceProfileInit "scala.aliases"
+sourceProfileInit "work.aliases"
+
+if [ "${PLATFORM}" = "Darwin" ]; then
+  sourceProfileInit "osx.env"
+  sourceProfileInit "osx.functions"
+  sourceProfileInit "osx.aliases"
 fi;
 
-# User specific environment and startup programs
+if [ "${PLATFORM}" = "Linux" ]; then
+  sourceProfileInit "linux.env"
+fi
 
 export PATH EDITOR GAEPATH PYTHONPATH RAILS_ENV MOZ_DISABLE_PANGO RUBYLIB
 export ERL_LIBS AUTOFEATURE RSPEC SSH_AUTH_SOCK SDL_AUDIODRIVER LANG LC_ALL
